-- 08132025_initial_schema.sql
-- Initial schema for Arreglo (credits + arrangements + subscriptions)

-- Enable required extensions
create extension if not exists pgcrypto;

-- Profiles hold per-user settings and credit balance
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  display_name text,
  plan text not null default 'free',
  credit_balance int not null default 0,
  stripe_customer_id text unique
);

-- Arrangements generated by users
create table if not exists public.arrangements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  genre text,
  tempo int,
  length_bars int,
  creativity int,
  sections jsonb not null,
  raw_response text,
  created_at timestamptz not null default now()
);

-- Usage logs for analytics/cost/limits
create table if not exists public.usage_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  action_type text not null, -- 'arrangement_generation' | 'image_analysis'
  tokens_in int default 0,
  tokens_out int default 0,
  cost_cents int default 0,
  meta jsonb,
  created_at timestamptz not null default now()
);

-- Subscriptions tracking
create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_customer_id text,
  stripe_subscription_id text unique,
  status text,
  current_period_end timestamptz,
  created_at timestamptz not null default now()
);

-- Indexes
create index if not exists idx_arrangements_user_id on public.arrangements(user_id);
create index if not exists idx_usage_logs_user_id on public.usage_logs(user_id);
create index if not exists idx_subscriptions_user_id on public.subscriptions(user_id);

-- Row Level Security
alter table public.user_profiles enable row level security;
-- user_profiles policies
drop policy if exists user_profiles_select on public.user_profiles;
create policy user_profiles_select
  on public.user_profiles for select
  using (auth.uid() = user_id);

drop policy if exists user_profiles_update_self on public.user_profiles;
create policy user_profiles_update_self
  on public.user_profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

alter table public.arrangements enable row level security;
-- arrangements policies
drop policy if exists arrangements_owner on public.arrangements;
create policy arrangements_owner
  on public.arrangements for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

alter table public.usage_logs enable row level security;
-- usage_logs policies
drop policy if exists usage_logs_owner_select on public.usage_logs;
create policy usage_logs_owner_select
  on public.usage_logs for select
  using (auth.uid() = user_id);

alter table public.subscriptions enable row level security;
-- subscriptions policies
drop policy if exists subscriptions_owner_select on public.subscriptions;
create policy subscriptions_owner_select
  on public.subscriptions for select
  using (auth.uid() = user_id);
